name: hotfix-backport-actions
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  check-merged-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: last_release
        run: |
          last_release_branch=$(git branch -r --list 'origin/release/1.[1-9][0-9][0-9]*' | sort | tail -n1)
          echo ${last_release_branch}