name: hotfix-backport-actions
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  check-merged-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
      - uses: actions/checkout@v2
      - run: git remote update --prune
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: last_release
        id: last_release
        run: |
          last_release_branch=$(git branch -r --list 'origin/release/1.[0-9]*' | sort | tail -n1)
          last_release_branch=${last_release_branch#*origin\/}
          echo '::set-output name=last_release::'${last_release_branch}
          echo ${last_release_branch}
      - name: backport to last release branch
        - id: create_backport_branch
        run: |
          release_br='${{ steps.last_release.outputs.last_release }}'
          echo ${release_br}
          release_version=${release_br#*release\/}
          backport_branch=backport/to_release_${release_version}
          echo ${backport_branch}
          git checkout master
          git checkout -b ${backport_branch}
          git push origin ${backport_branch}
          echo '::set-output name=backport_branch::'${backport_branch}
      - name: Auto create PR if need backport
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.create_backport_branch.outputs.backport_branch }}
          pr_title: Backport/${{ steps.last_release.outputs.last_release }}
          pr_allow_empty: true
          destination_branch: ${{ steps.last_release_branch.outputs.last_release }}
          
