name: hotfix-backport-actions
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  check-merged-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
      - uses: actions/checkout@v2
      - run: git remote update --prune
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: last_release
        id: last_release
        run: |
          last_release_branch=$(git branch -r --list 'origin/release/1.[0-9]*' | sort | tail -n1)
          echo '::set-output name=last_release::'${last_release_branch}
          echo ${last_release_branch}
      - name: echo last_release
        run: |
          release_br='${{ steps.last_release.outputs.last_release }}'
          echo ${release_br}
          release_version=${release_br#*release\/}
          backport_branch=backport/to_release_${release_version}
          echo ${backport_branch}
      # - name: back to last release
      #   run: |
      #     git checkout master
      #     git checkout -b backport/to_${{ steps.last_release.outputs.last_release }}