name: hotfix-backport-actions
on:
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]
  push:
    branches:
      - master
      - hotfix/.*
jobs:
  check-merged-pull-request:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: node -v
