name: hotfix-backport-actions
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  check-merged-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: last_release
        id: last_release
        run: |
          git fetch origin release/1.3.0
          last_release_branch=$(git branch -r --list 'origin/release/1.[0-9]*' | sort | tail -n1)
          echo '::set-output name=last_release::'${last_release_branch}
      - name: echo last_release
        run: echo "${{ steps.last_release.outputs.last_release }}"