name: hotfix-backport-actions
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  backport-to-release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git remote update --prune
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: get last release branch version
        id: last_release_branch
        run: |
          last_release_branch=$(git branch -r --list 'origin/release/1.[0-9]*' | sort | tail -n1)
          last_release_branch=${last_release_branch#*origin\/}
          git checkout ${last_release_branch}
          yarn set-version-output # version = 1.1.0
      - name: create backport to release branch 
        id: backport_release_branch
        run: |
          backport_branch_name=backport/to_release_${{ steps.last_release_branch.outputs.version }}
          echo ${backport_branch_name} # backport/to_release_1.1.0
          git checkout master
          git checkout -b ${backport_branch_name}
          git push origin ${backport_branch_name}
          echo '::set-output name=name::'${backport_branch_name} # backport/to_release_1.1.0
      - name: Auto create PR if need backport to release
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.backport_release_branch.outputs.name }} # backport/to_release_1.1.0
          pr_title: Backport/to_release${{ steps.last_release_branch.outputs.version }} # Backport/to_release_1.1.0
          pr_body: |
            "It automatted PR from ${{ github.event.pull_request.head_ref}} backport to ${{ github.event.pull_request.ref}}" 
          pr_allow_empty: true
          destination_branch: release/${{ steps.last_release_branch.outputs.version }} # release/1.1.0
      
  backport-to-develop:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git remote update --prune
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'          
      - name: get develop version
        id: develop_branch
        run: |
          git checkout develop
          yarn set-version-output
      - name: create backport branch to develop
        id: create_backport_develop_branch
        run: |
          git checkout master
          backport_branch=backport/to_develop_${{ steps.develop_branch.outputs.version}} # backport/to_develop_1.3.0-alpha.0
          git checkout -b ${backport_branch}
          git push origin ${backport_branch}
          echo '::set-output name=backport_branch::'${backport_branch} # backport/to_develop_1.3.0-alpha.0
      - name: Auto create PR if need backport to develop
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.create_backport_develop_branch.outputs.backport_branch }} # backport/to_develop_1.3.0-alpha.0
          pr_title: Backport/to_develop_${{ steps.develop_branch.outputs.version }} # Backport/to_develop_1.3.0-alpha.0
          pr_body: |
            "It automatted PR from ${{ github.event.pull_request.head_ref}} backport to ${{ github.event.pull_request.ref}}" 
          pr_allow_empty: true
          destination_branch: develop