name: hotfix-backport-actions
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  check-merged-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
  check-not-merged-pull-request:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it i not merged pull request'