name: hotfix-backport-actions
on:
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]
  push:
    branches:
      - master
      - hotfix/.*
jobs:
  check-merged-pull-request:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it is merged pull request'
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          title: 'backport master to develop'
