on:
  push:
    branches:
      - hotfix/**
jobs:
  test-github-context:
    runs-on: ubuntu-latest
    steps:
      - run: echo github ref:: '${{github.ref}}'
      - run: echo github head_ref:: '${{github.head_ref}}'
    